<?php
/**
 * Created by PhpStorm.
 * User: Mzapeka
 * Date: 17.11.15
 * Time: 22:35
 */

namespace System;

class MyExcelFile {
    private $row = 4;
    private $itemCounter = 1;
    private $objPHPExcel;
    private $fileName = "report.xlsx";

 public function __construct(){
    error_reporting(E_ALL);
    /** Include PHPExcel */
    require_once dirname(__FILE__) . '/Classes/PHPExcel.php';
    define('EOL',(PHP_SAPI == 'cli') ? PHP_EOL : '<br />');
// Create new PHPExcel object
   // echo date('H:i:s') , " Create new PHPExcel object" , EOL;
    $this->objPHPExcel = new \PHPExcel();
// Set document properties
   // echo date('H:i:s') , " Set document properties" , EOL;
    $this->objPHPExcel->getProperties()->setCreator("CeneoParser")
        ->setLastModifiedBy("CeneoParser")
        ->setTitle("Office 2007 XLSX Document")
        ->setSubject("Office 2007 XLSX Document")
        ->setDescription("Document for Office 2007 XLSX, generated by CeneoParser.")
        ->setCategory("CeneoParser result file");
    $this->createTemplate();
}
    protected function createTemplate(){
        $this->objPHPExcel->setActiveSheetIndex(0);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 1, 'Data of creation:');
        $this->objPHPExcel->getActiveSheet()->setCellValue('C1', \PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
        $this->objPHPExcel->getActiveSheet()->getStyle('C1')->getNumberFormat()->setFormatCode(\PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);

        $this->objPHPExcel->getActiveSheet()->setCellValue('A3', 'ID');
        $this->objPHPExcel->getActiveSheet()->setCellValue('B3', 'Photo');
        $this->objPHPExcel->getActiveSheet()->setCellValue('C3', 'Category');
        $this->objPHPExcel->getActiveSheet()->setCellValue('D3', 'Sub category');
        $this->objPHPExcel->getActiveSheet()->setCellValue('E3', 'Name');
        $this->objPHPExcel->getActiveSheet()->setCellValue('F3', 'Min Price');
        $this->objPHPExcel->getActiveSheet()->setCellValue('G3', 'On shop');
        $this->objPHPExcel->getActiveSheet()->setCellValue('H3', 'Pic');

        // Set cell number formats
        //$objPHPExcel->getActiveSheet()->getStyle('E4:E13')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_EUR_SIMPLE);

// Set column widths
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(12);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(36);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
        $this->objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(28);

        $this->objPHPExcel->getActiveSheet()->getStyle('A3:H3')->getBorders()->getAllBorders()->setBorderStyle(true);
/*// Set fonts
        $this->objPHPExcel->getActiveSheet()->getStyleByColumnAndRow('B1')->getFont()->setName('Candara');
        $this->objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
        $this->objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
        $this->objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
        $this->objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

        $this->objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
        $this->objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

        $this->objPHPExcel->getActiveSheet()->getStyle('D13')->getFont()->setBold(true);
        $this->objPHPExcel->getActiveSheet()->getStyle('E13')->getFont()->setBold(true);

// Set alignments
        $objPHPExcel->getActiveSheet()->getStyle('D11')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);
        $objPHPExcel->getActiveSheet()->getStyle('D12')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);
        $objPHPExcel->getActiveSheet()->getStyle('D13')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);

        $objPHPExcel->getActiveSheet()->getStyle('A18')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_JUSTIFY);
        $objPHPExcel->getActiveSheet()->getStyle('A18')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

        $objPHPExcel->getActiveSheet()->getStyle('B5')->getAlignment()->setShrinkToFit(true);*/

    }

    public function inputData($data = array(), $imgIncert = false){
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, $this->row, $this->itemCounter++);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $this->row, $data['photo']);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $this->row, $data['cat']);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $this->row, $data['subcat']);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $this->row, $data['name']);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $this->row, $data['minPrice']);
        $this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $this->row, $data['shopNumb']);
        $this->objPHPExcel->getActiveSheet()->getStyle('A'.$this->row.':H'.$this->row)->getBorders()->getAllBorders()->setBorderStyle(true);
        $this->objPHPExcel->getActiveSheet()->getRowDimension($this->row)->setRowHeight(90);
        if ($imgIncert){
            file_put_contents("img/img".$this->row.".jpg",file_get_contents($data['photo']));
            // Add a drawing to the worksheet
            $objDrawing = new \PHPExcel_Worksheet_Drawing();
            $objDrawing->setPath("img/img".$this->row.".jpg");
            $objDrawing->setCoordinates('H'.$this->row);
            if ($objDrawing->getHeight() > 90){
                $objDrawing->setHeight(90);
            }
            $objDrawing->setWorksheet($this->objPHPExcel->getActiveSheet());

        }
        $this->row++;
    }

    public function setFileName($fileName){
        $this->fileName = $fileName.".xlsx";
    }

    public function saveFile(){
        $objWriter = new \PHPExcel_Writer_Excel2007($this->objPHPExcel);
        $objWriter->save($this->fileName);
        return $this->fileName;
    }
}